In [10]:
import pandas as pd
df1=pd.read_csv('winequality-red.csv',sep=';')
df1

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [13]:
df1.columns
independent=df1[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density','pH', 'sulphates', 'alcohol']]
independent

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [14]:
dependent=df1['quality']
dependent

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def categorize_quality(score):
    if score >= 7:
        return 'Best'
    elif score >= 5:
        return 'Average'
    else:
        return 'Poor'

dependent = dependent.apply(categorize_quality)
dependent

0       Average
1       Average
2       Average
3       Average
4       Average
         ...
1594    Average
1595    Average
1596    Average
1597    Average
1598    Average
Name: quality, Length: 1599, dtype: object

In [16]:
#split training and testing data in 75-25 ratio
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
y=df1[['quality']].copy()
features=['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']
x=df1[features].copy()

X_train, X_test, Y_train, Y_test = train_test_split(independent,dependent, train_size=0.75,test_size=0.25, random_state=40)
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1316,5.4,0.74,0.00,1.2,0.041,16.0,46.0,0.99258,4.01,0.59,12.5
1507,7.5,0.38,0.57,2.3,0.106,5.0,12.0,0.99605,3.36,0.55,11.4
849,6.4,0.63,0.21,1.6,0.080,12.0,32.0,0.99689,3.58,0.66,9.8
82,7.4,0.50,0.47,2.0,0.086,21.0,73.0,0.99700,3.36,0.57,9.1
644,9.9,0.54,0.45,2.3,0.071,16.0,40.0,0.99910,3.39,0.62,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1016,8.9,0.38,0.40,2.2,0.068,12.0,28.0,0.99486,3.27,0.75,12.6
165,7.8,0.63,0.48,1.7,0.100,14.0,96.0,0.99610,3.19,0.62,9.5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0
219,7.8,0.53,0.33,2.4,0.080,24.0,144.0,0.99655,3.30,0.60,9.5
1350,9.0,0.60,0.29,2.0,0.069,32.0,73.0,0.99654,3.34,0.57,10.0

In [17]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, Y_train)
y_pred = rf_model.predict(X_test)
y_pred

array(['Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Best', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Best', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Best', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Best', 'Average', 'Average',
       'Average', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Best', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Best', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Best', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Best', 'Best',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Best', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Best', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Best', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Best', 'Best', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Best', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Best', 'Average', 'Average', 'Average', 'Average', 'Best',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Best', 'Best',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Best', 'Best', 'Average', 'Average', 'Average', 'Average', 'Best',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Best', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Best', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Best',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Best', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Best', 'Average', 'Best',
       'Average', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Best', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Best', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Best', 'Average', 'Average', 'Best', 'Average',
       'Average', 'Average', 'Average'], dtype=object)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
c=confusion_matrix(Y_test,y_pred)
print(c)

[[314  10   0]
 [ 30  31   0]
 [ 15   0   0]]

In [19]:
recall = recall_score(Y_test, y_pred, average='weighted')
recall

0.8625

In [20]:
f1 = f1_score(Y_test, y_pred, average='weighted')
f1

0.8374691384606551

In [21]:
#predict the target values in testing set
from sklearn.ensemble import RandomForestClassifier
rf1_model = RandomForestClassifier(n_estimators=200,criterion='gini',max_depth=12,min_samples_split=12,min_samples_leaf=12,max_features='log2',random_state=42)
rf1_model.fit(X_train, Y_train)
y_pred1 = rf1_model.predict(X_test)
y_pred1
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
c1=confusion_matrix(Y_test,y_pred1)
print(c1)

[[320   4   0]
 [ 43  18   0]
 [ 15   0   0]]

In [22]:
accuracy1 = accuracy_score(Y_test, y_pred1)*100
accuracy1

84.5

In [23]:
recall = recall_score(Y_test, y_pred1, average='weighted')
recall

0.845

In [24]:
f1 = f1_score(Y_test, y_pred1, average='weighted')
f1

0.8046061167747913

In [25]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
#As the deafaul value is gini ,if we dont't specify it will select gini criteria by default
clf =DecisionTreeClassifier(criterion="gini",max_leaf_nodes=5,random_state=0)
clf.fit(X_train,Y_train)
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
y_predicted=clf.predict(X_test)
print(y_predicted)

['Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Best'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Best' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Best' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Best'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Best'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Best' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Best' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Best' 'Best' 'Average' 'Best' 'Average'
 'Best' 'Best' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Best' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Best' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Best' 'Average' 'Average'
 'Average' 'Average' 'Best' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Best' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Best'
 'Average' 'Best' 'Average' 'Average' 'Average' 'Best' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Best'
 'Average' 'Average' 'Average' 'Best' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Best' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Best' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Best' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Best' 'Average' 'Average' 'Average' 'Average' 'Best' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Best' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Best' 'Best'
 'Average' 'Average' 'Average' 'Average' 'Best' 'Average' 'Average'
 'Average' 'Best' 'Average' 'Average' 'Average' 'Average' 'Average' 'Best'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Best'
 'Average' 'Average' 'Average' 'Average' 'Best' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Best' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average']

In [26]:
a=accuracy_score(Y_test,y_predicted)*100
c=confusion_matrix(Y_test,y_predicted)
print("Confusion Matrix:\n", c)
print("Accuracy:", a)

Confusion Matrix:
 [[310  14   0]
 [ 39  22   0]
 [ 15   0   0]]
Accuracy: 83.0

6.	Perform normalization on numerical features

7.	Build a Random Forest classification model using Sklearn with default parameters. Predict the target values in the testing set.

8.	Check the performance of model using confusion matrix

9.	Calculate the accuracy, PR, RR and F1-score

10.	Playing with Random Forest: Change the following parameters of the random forest and analyze their performance for training and testing using the evaluation measures. (20) 
a.	n_estimators 
b.	criterion{“mse”, “mae”} 
c.	max_depth 
d.	min_samples_split  
e.	min_samples_leaf 
f.	max_features 
g.	random_state

11.	Compare the performance of the Random Forest model with Decision Tree Model.